# Generated by Django 3.0.7 on 2020-07-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_header',
            name='parent_sl_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfqsite.Part_Header'),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='sl_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
