# Generated by Django 3.0.7 on 2020-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0002_auto_20200712_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='armwpp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='base_material_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fpwp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='shipping_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Material2',
        ),
    ]
