# Generated by Django 3.0.7 on 2020-07-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0002_auto_20200708_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctpp',
            name='assembly',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='axis5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='bta',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='cla',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='deburring',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='edm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='grinding',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='hmc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='inspection',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='lapping',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='mca3axis',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='mca4axis',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ctpp',
            name='tma',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_d1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_d2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_l',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_t',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_total_weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_w',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='axis5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='bta',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='cla',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='edm',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='grinding',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='hmc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='mca3axis',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='mca4axis',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='msut',
            name='tma',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='base_material_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='ebq_customer_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='material_shipping_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='nre_amortizing_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='otrmac',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='otspsuc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='ottc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='target_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='file_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
