# Generated by Django 3.0.7 on 2020-07-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0003_auto_20200706_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_qty',
            new_name='qantity',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='sps',
            old_name='solid',
            new_name='solid_film',
        ),
    ]
