# Generated by Django 3.0.7 on 2020-07-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0003_auto_20200709_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sps',
            name='hardware_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sps',
            name='hardware_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='cross_section',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_d1_unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_d2_unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_l_unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_t_unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_w_unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='ccs_quote_assumptions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='dltiw_fai',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='dltiw_production',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='dltiw_serial_production',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='hardware_supplier',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='material_supplier',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='file_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='part_header',
            name='program',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='file_path',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sps',
            name='fpi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='ht',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='mpi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='pmr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='primer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='solid_film',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sps',
            name='surface_treatment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Burden_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FloatField(default=1)),
                ('hardware', models.FloatField(default=1)),
                ('subcontract', models.FloatField(default=1)),
                ('sp', models.FloatField(default=1)),
                ('tracker_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfqsite.RFQ')),
            ],
        ),
    ]
