# Generated by Django 3.0.7 on 2020-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0004_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='mcrftp_5axis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_bta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_cla',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_edm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_grinding',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_hmc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_mca3axis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_mca4axis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mcrftp_tma',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='mtl_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='spl_process_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='total_hardware_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='rm_density',
            field=models.FloatField(default=0, null=True),
        ),
    ]
