# Generated by Django 3.0.7 on 2020-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0005_auto_20200713_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='usd_thb',
            field=models.FloatField(default=35),
        ),
    ]
