# Generated by Django 3.0.7 on 2020-07-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0006_auto_20200706_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_rate',
            old_name='duburring',
            new_name='deburring',
        ),
    ]
