# Generated by Django 3.0.7 on 2020-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0007_auto_20200706_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='qty_per_unit',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='qantity',
            field=models.FloatField(default=1),
        ),
    ]
