# Generated by Django 3.0.7 on 2020-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0007_extenduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(default=2)),
                ('user', models.ManyToManyField(to='rfqsite.ExtendUser')),
            ],
        ),
    ]
