# Generated by Django 3.0.7 on 2020-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0008_auto_20200706_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_current_year',
            field=models.DateTimeField(verbose_name='date publish'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year1',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year2',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year3',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year4',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year5',
            field=models.FloatField(default=100),
        ),
    ]
