# Generated by Django 3.0.7 on 2020-07-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0008_auto_20200715_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(default=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfqsite.Roles'),
        ),
    ]
