# Generated by Django 3.0.7 on 2020-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0009_auto_20200715_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='type',
        ),
        migrations.AddField(
            model_name='roles',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
