# Generated by Django 3.0.7 on 2020-07-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0010_auto_20200706_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctpp',
            old_name='duburring',
            new_name='deburring',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='qantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='msut',
            old_name='mca5axis',
            new_name='mca4axis',
        ),
    ]
