# Generated by Django 3.0.7 on 2020-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0010_auto_20200715_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='forecast_current_year',
        ),
        migrations.AddField(
            model_name='rfq',
            name='current_year',
            field=models.IntegerField(default=2020),
        ),
    ]
