# Generated by Django 3.0.7 on 2020-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0014_auto_20200716_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_costing',
            name='ebq_ccs_qty',
            field=models.FloatField(default=0, null=True),
        ),
    ]
