# Generated by Django 3.0.7 on 2020-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0015_part_costing_ebq_ccs_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_header',
            name='type',
            field=models.CharField(default='Part', max_length=50),
        ),
    ]
