# Generated by Django 3.0.7 on 2020-07-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0016_part_header_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP_Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
