# Generated by Django 3.0.7 on 2020-07-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0019_auto_20200718_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='total_machine_cost',
            field=models.FloatField(default=0),
        ),
    ]
