# Generated by Django 3.0.7 on 2020-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0020_output_total_machine_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
    ]
