# Generated by Django 3.0.7 on 2020-07-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0022_act_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_master',
            name='rate',
        ),
    ]
