# Generated by Django 3.0.7 on 2020-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0024_auto_20200719_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_set',
            name='mcrftp',
            field=models.FloatField(default=0),
        ),
    ]
