# Generated by Django 3.0.7 on 2020-07-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0025_mc_set_mcrftp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctpp',
            name='sl_no',
        ),
        migrations.RemoveField(
            model_name='msut',
            name='sl_no',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_5axis',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_bta',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_cla',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_edm',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_grinding',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_hmc',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_mca3axis',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_mca4axis',
        ),
        migrations.RemoveField(
            model_name='output',
            name='mcrftp_tma',
        ),
        migrations.DeleteModel(
            name='Active_Rate',
        ),
        migrations.DeleteModel(
            name='CTPP',
        ),
        migrations.DeleteModel(
            name='MSUT',
        ),
    ]
