# Generated by Django 3.0.7 on 2020-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0026_auto_20200722_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='ccs_tracker_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='tracker_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
