# Generated by Django 3.0.7 on 2020-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0027_auto_20200722_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='hardware_burden_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='material_burden_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='sp_burden_cost',
            field=models.FloatField(default=0),
        ),
    ]
