# Generated by Django 3.0.7 on 2020-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0029_auto_20200723_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='last_generate',
            field=models.DateTimeField(null=True, verbose_name='date publish'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_year5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='qty_per_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='ebq_ccs_qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='part_costing',
            name='ebq_customer_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
