# Generated by Django 3.0.7 on 2020-07-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0031_auto_20200726_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=0)),
                ('no', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=200)),
                ('program', models.CharField(default='', max_length=200)),
                ('current_year', models.IntegerField(default=2020)),
                ('forecast_year1', models.IntegerField(default=0)),
                ('forecast_year2', models.IntegerField(default=0)),
                ('forecast_year3', models.IntegerField(default=0)),
                ('forecast_year4', models.IntegerField(default=0)),
                ('forecast_year5', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('material_cost', models.FloatField(default=0)),
                ('surface_treatment_cost', models.FloatField(default=0)),
                ('hardware_cost', models.FloatField(default=0)),
                ('total_manufacturing_cost', models.FloatField(default=0)),
                ('ccs_ewp', models.FloatField(default=0)),
                ('ebq_customer_qty', models.IntegerField(default=0, null=True)),
                ('aeqfc', models.FloatField(default=0)),
                ('ottc', models.FloatField(default=0, null=True)),
                ('ccs_quote_assumptions', models.CharField(default='', max_length=200)),
                ('dltiw_fai', models.CharField(default='', max_length=200)),
                ('dltiw_serial_production', models.CharField(default='', max_length=200)),
                ('dltiw_production', models.CharField(default='', max_length=200)),
                ('tracker_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfqsite.RFQ')),
            ],
        ),
    ]
