# Generated by Django 3.0.7 on 2020-07-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0032_customer_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_part',
            name='aeqfc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='aeqfc',
            field=models.IntegerField(default=0),
        ),
    ]
