# Generated by Django 3.0.7 on 2020-07-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0036_rfq_ccs_rfq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='ccs_tracker_no',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='description',
        ),
        migrations.AlterField(
            model_name='part_header',
            name='no',
            field=models.CharField(default='', max_length=200),
        ),
    ]
