# Generated by Django 3.0.7 on 2020-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0037_auto_20200801_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_master',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sp_master',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
