# Generated by Django 3.0.7 on 2020-08-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfqsite', '0038_auto_20200801_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Part',
        ),
    ]
